main: main.c Lab3IO.c
	gcc -g -Wall main.c Lab3IO.c -o main -fopenmp

datagen: datagen.c Lab3IO.c
	gcc -g -Wall datagen.c Lab3IO.c -o datagen

serialtester: serialtester.c Lab3IO.c
	gcc serialtester.c Lab3IO.c -o serialtester -lm